export { default as Navbar } from './Navigation/Navbar'
export { default as About } from './About/About'
export { default as Projects } from './Projects/Projects'
export { default as Contact } from './Contact/Contact'
export { default as Resume } from './Resume/Resume'
export { default as Footer } from './Footer/Footer'